spring.application.name=price-fetcher
server.port=8081


spring.datasource.url=jdbc:postgresql://localhost:5433/crypto_monitoring
spring.datasource.username=crypto
spring.datasource.password=crypto123
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.hikari.connection-timeout=10000
spring.datasource.hikari.maximum-pool-size=10


spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect


spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration


spring.data.redis.host=localhost
spring.data.redis.port=6379


spring.task.scheduling.pool.size=2


app.binance.api-url=https://api.binance.com/api/v3/ticker/price
app.binance.symbols=BTCUSDT,ETHUSDT,SOLUSDT


management.endpoints.web.exposure.include=health,info,metrics
